unused var + pessimizing move
```
/home/julien/Software/Others/EnergyPlus2/src/EnergyPlus/EMSManager.cc:2022:32: error: moving a temporary object prevents copy elision [-Werror,-Wpessimizing-move]
 2022 |     auto tup = std::make_tuple(std::move(Util::makeUPPER(objType)), std::move(Util::makeUPPER(objName)), std::move(Util::makeUPPER(controlTypeName)));
```